### ISSUE TITLE
@AdvancedTowing auf dem Server hinzufügen

### ISSUE THREAD

**Issue by christian2526** [TaskForce47/Domination-Lingor#49]
Diesen Mod bitte Serverseitig installieren, ist nur server side, also nicht in die Repo packen.

http://www.armaholic.com/page.php?id=30575

Die Config ist bereits in der Domi und funktioniert.

**Comment by 4Lucke** [comment]
Kann ich momentan nicht machen. Mindblaster oder Dragon müssen das
übernehmen.


Am 06.02.2017 11:42 vorm. schrieb "Christian" <notifications@github.com>:

Assigned #49 <https://github.com/TaskForce47/Domination-Lingor/issues/49>
to @4Lucke <https://github.com/4Lucke>.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/TaskForce47/Domination-Lingor/issues/49#event-950081579>,
or mute the thread

**Comment by mindbl4ster** [comment]
done
